/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
 * Generated on: 10-May-2022 15:29:59
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 50
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2020b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int NL = 50;
extern const float N[50] = {
   0.008808732033, 0.004420365673, 0.005464280955, 0.006614868063, 0.007867260836,
   0.009212484583,  0.01064862777,  0.01216090471,  0.01373990905,  0.01536158659,
    0.01701700129,  0.01868805103,  0.02035579644,  0.02198681794,   0.0235851761,
    0.02511408925,   0.0265548192,  0.02789602801,  0.02911192551,  0.03018962964,
    0.03111197427,  0.03186466917,  0.03244063258,  0.03283003345,  0.03302348033,
    0.03302348033,  0.03283003345,  0.03244063258,  0.03186466917,  0.03111197427,
    0.03018962964,  0.02911192551,  0.02789602801,   0.0265548192,  0.02511408925,
     0.0235851761,  0.02198681794,  0.02035579644,  0.01868805103,  0.01701700129,
    0.01536158659,  0.01373990905,  0.01216090471,  0.01064862777, 0.009212484583,
   0.007867260836, 0.006614868063, 0.005464280955, 0.004420365673, 0.008808732033
};
